#!/bin/bash

type exifautotran  >/dev/null 2>&1 || { echo >&2 "exifautotran missing :(";  exit 1; }
type rename-photos >/dev/null 2>&1 || { echo >&2 "rename-photos missing :("; exit 1; }
type prename       >/dev/null 2>&1 || { echo >&2 "prename missing :(";       exit 1; }

INCOMING=$HOME/incoming

# Panasonic SD card
find /media/F009-64A5/ -iname '*jpg' -exec mv -vb {} $INCOMING \;
find /media/F009-64A5/ -iname '*mov' -exec mv -vb {} $INCOMING \;

# Canon SD card
find /media/CANON_DC -iname '*jpg' -exec mv -vb {} $INCOMING \;
find /media/CANON_DC -iname '*avi' -exec mv -vb {} $INCOMING \;

# What the hell? Panasonic SD card's name changed!
find /media/tions\:\ -Wal/ -iname '*jpg' -exec mv -vb {} $INCOMING \;
find /media/tions\:\ -Wal/ -iname '*mov' -exec mv -vb {} $INCOMING \;

# Panasonic SD card's name changed again!?
find /media/-strict-fie/ -iname '*jpg' -exec mv -vb {} $INCOMING \;
find /media/-strict-fie/ -iname '*mov' -exec mv -vb {} $INCOMING \;

# And again...
find /media/carlo/F009-64A5 -iname '*jpg' -exec mv -vb {} $INCOMING \;
find /media/carlo/F009-64A5 -iname '*mov' -exec mv -vb {} $INCOMING \;

# Remove Canon S2 IS thumbnails
find /media/CANON_DC -iname '*thm' -exec rm -vb {} \;

# sshfs mount of Galaxy S3
s3=$HOME/sshdroid//mnt/sdcard/DCIM

find ${s3}/Camera         -iname '*jpg' -exec mv -vb {} $INCOMING \;
find ${s3}/Camera         -iname '*mp4' -exec mv -vb {} $INCOMING \;
find ${s3}/.thumbnails    -type f -exec rm -v {} \;

cd $INCOMING

find . -iname '*jpg' -exec exifautotran {} \;

find . -type f -exec chmod 644 {} \;

prename 's/JPG/jpg/g' *JPG

rename-photos

cd

sudo umount /media/F009-64A5/
sudo umount /media/CANON_DC
sudo umount /dev/mmcblk0p1
sudo umount $HOME/sshdroid
sudo umount /media/carlo/F009-64A5
